// webpack/webpack5-vue/src/App.vue
<template>
    <div>
        <h1 class="title">Hello app</h1>
        <el-button type="primary">按钮</el-button>
        <ul>
            <li>
                <router-link to="/home">Home</router-link>
            </li>
            <li>
                <router-link to="/about">About</router-link>
            </li>
        </ul>
        <router-view />
    </div>
</template>

<script>
    export default {
        name: "App",
    }
</script>

<style>
.title {
    color: pink;
}
</style>

// webpack/webpack5-react/src/App.jsx
import React, { Suspense, lazy } from "react";
import { Link, Routes, Route } from "react-router-dom";
import { Button } from "antd";

// import Home from "./pages/Home";
// import About from "./pages/About";

const Home = lazy(() => import(/* webpackChunkName: 'home' */ "./pages/Home"));
const About = lazy(() =>
  import(/* webpackChunkName: 'about' */ "./pages/About")
);

function App() {
  return (
    <div>
      <h1>App</h1>
      <Button type="primary">按钮</Button>
      <ul>
        <li>
          <Link to="/home">Home</Link>
        </li>
        <li>
          <Link to="/about">About</Link>
        </li>
      </ul>
      <Suspense fallback={<div>loading...</div>}>
        <Routes>
          <Route path="/home" element={<Home />}></Route>
          <Route path="/about" element={<About />}></Route>
        </Routes>
      </Suspense>
    </div>
  );
}

export default App;
